# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'findWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_findDialog(object):
    def setupUi(self, findDialog):
        findDialog.setObjectName("findDialog")
        findDialog.resize(651, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/chazhao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        findDialog.setWindowIcon(icon)
        self.lineEdit = QtWidgets.QLineEdit(findDialog)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 400, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox = QtWidgets.QCheckBox(findDialog)
        self.checkBox.setGeometry(QtCore.QRect(40, 110, 200, 30))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(findDialog)
        self.pushButton.setGeometry(QtCore.QRect(500, 30, 100, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(findDialog)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 90, 100, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(findDialog)
        self.pushButton_4.setGeometry(QtCore.QRect(439, 150, 161, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(findDialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 70, 400, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(findDialog)
        self.label.setGeometry(QtCore.QRect(220, 150, 200, 30))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(findDialog)
        QtCore.QMetaObject.connectSlotsByName(findDialog)

    def retranslateUi(self, findDialog):
        _translate = QtCore.QCoreApplication.translate
        findDialog.setWindowTitle(_translate("findDialog", "查找和替换"))
        self.lineEdit.setPlaceholderText(_translate("findDialog", "查找语句"))
        self.checkBox.setText(_translate("findDialog", "使用正则表达式"))
        self.pushButton.setText(_translate("findDialog", "查找"))
        self.pushButton_3.setText(_translate("findDialog", "替换"))
        self.pushButton_4.setText(_translate("findDialog", "替换所有"))
        self.lineEdit_2.setPlaceholderText(_translate("findDialog", "替换语句"))
from  ui.resource import icon_rc
