# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'functionWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_functionDialog(object):
    def setupUi(self, functionDialog):
        functionDialog.setObjectName("functionDialog")
        functionDialog.resize(800, 600)
        functionDialog.setMinimumSize(QtCore.QSize(800, 600))
        functionDialog.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        functionDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/fengxian.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        functionDialog.setWindowIcon(icon)
        self.lineEdit = QtWidgets.QLineEdit(functionDialog)
        self.lineEdit.setGeometry(QtCore.QRect(30, 50, 130, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(functionDialog)
        self.comboBox.setGeometry(QtCore.QRect(180, 50, 150, 32))
        self.comboBox.setStyleSheet("min-height:30px")
        self.comboBox.setIconSize(QtCore.QSize(30, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(functionDialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(350, 50, 300, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tableWidget = QtWidgets.QTableWidget(functionDialog)
        self.tableWidget.setGeometry(QtCore.QRect(30, 100, 620, 460))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.label = QtWidgets.QLabel(functionDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 130, 30))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(functionDialog)
        self.label_2.setGeometry(QtCore.QRect(180, 20, 150, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(functionDialog)
        self.label_3.setGeometry(QtCore.QRect(350, 20, 150, 30))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(functionDialog)
        self.pushButton.setGeometry(QtCore.QRect(670, 50, 100, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(functionDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 100, 100, 30))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(functionDialog)
        QtCore.QMetaObject.connectSlotsByName(functionDialog)

    def retranslateUi(self, functionDialog):
        _translate = QtCore.QCoreApplication.translate
        functionDialog.setWindowTitle(_translate("functionDialog", "风险函数管理"))
        self.comboBox.setItemText(0, _translate("functionDialog", "低危险"))
        self.comboBox.setItemText(1, _translate("functionDialog", "中等危险"))
        self.comboBox.setItemText(2, _translate("functionDialog", "危险"))
        self.comboBox.setItemText(3, _translate("functionDialog", "很危险（或稍小，取决于实现）"))
        self.comboBox.setItemText(4, _translate("functionDialog", "很危险"))
        self.comboBox.setItemText(5, _translate("functionDialog", "最危险"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("functionDialog", "函数名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("functionDialog", "函数危险等级"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("functionDialog", "建议解决方法"))
        self.label.setText(_translate("functionDialog", "函数名"))
        self.label_2.setText(_translate("functionDialog", "函数危险等级"))
        self.label_3.setText(_translate("functionDialog", "建议解决方法"))
        self.pushButton.setText(_translate("functionDialog", "添加"))
        self.pushButton_2.setText(_translate("functionDialog", "删除"))
from ui.resource import icon_rc
